### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by peterjuras** [jpodwys/express-stream#6]
Hi!

Your streaming implementation looks great for streaming server-side rendered templates! Do you also cache the compiled templates like express does by default?

**Comment by jpodwys** [comment]
I'm not doing anything extra to cache the templates, but my code does call express's `res.render` internally. So if express is caching them by default, then it seems likely that my library is simply consuming the cached version after initial render.

**Comment by peterjuras** [comment]
Thanks! I was looking for a confirmation since your readme didn't mention it, but it makes sense that the provided render method is used. I was only confused because your "manual" example rendered the ejs templates itself.

**Comment by jpodwys** [comment]
That's a good point. I've simply wrapped the existing `render` call. Hope it works out for you!
